= Systemd
:idprefix:
:idseparator: -
:docinfo: shared

== Automatic systemd service generation

A systemd service file is generated automatically when you create the broker via cli. The file is available at `pathToBrokerInstance/etc/artemis.service`.

You might want to tweak or add additional configuration inside the service file, for example:

* uncomment and/or change `User` with which to run the service, to avoid running as root
* add `Nice` to tweak niceness of the java process
* add `Alias`
* increase or decrease `TimeoutStopSec` and `RestartSec`
* change `ARTEMIS_CONSOLE_PATTERN` and `ARTEMIS_FILE_LEVEL`; by default the service logs to journald only, without the date and time (see xref:logging.adoc[Logging])

You can read more about systemd https://systemd.io/[here].

== Enabling systemd service

You can now use `systemctl` commands to start/stop/restart the service, named `artemisTest`:

[,console]
----
systemctl start   artemisTest
systemctl stop    artemisTest
systemctl restart artemisTest
----

You can read the systemctl man page https://man7.org/linux/man-pages/man1/systemctl.1.html[here].
