= Systemd
:idprefix:
:idseparator: -
:docinfo: shared

== Automatic systemd service generation

A systemd service file is generated automatically when you create the broker via cli. The file is available at `pathToBrokerInstance/etc/artemis.service`.

You might want to tweak or add additional configuration inside the service file, for example:

* uncomment and/or change `User` with which to run the service, to avoid running as root
* add `Nice` to tweak niceness of the java process
* add `Alias`
* increase or decrease `TimeoutStopSec` and `RestartSec`
* change `ARTEMIS_CONSOLE_PATTERN` and `ARTEMIS_FILE_LEVEL`; by default the service logs to journald only. (See xref:logging.adoc[Logging])

You can read more about systemd https://systemd.io/[here].

== Logging

When running as a service, the broker logs to journald only. Read the logs with `journalctl -u artemis`, or only warnings and errors with `journalctl -u artemis -p warning`.

[WARNING]
====
* With journald's default `Storage=auto`, logs are only kept in memory, and lost on reboot, unless the `/var/log/journal` directory exists.
Create it, or set `Storage=persistent` in `/etc/systemd/journald.conf`, to keep logs across reboots.
* journald rate-limits each service (by default 10000 messages per 30 seconds) and drops messages above the limit.
If you enable `DEBUG`/`TRACE` or audit logging, raise the limit with `LogRateLimitIntervalSec=` and `LogRateLimitBurst=` in the service file.
====

== Enabling systemd service

You can now use `systemctl` commands to start/stop/restart the service, named `artemis`:

[,console]
----
systemctl start   artemis
systemctl stop    artemis
systemctl restart artemis
----

You can read the systemctl man page https://man7.org/linux/man-pages/man1/systemctl.1.html[here].
